document.documentElement.classList.add((()=>(/Mobile|Android|iPhone|iPad/i.test(navigator.userAgent)?'mobile':'desktop'))());var A=document.querySelector('.network'),c=document.querySelector('.theme-toggle'),d=()=>{const D=!c.matches('[aria-pressed=true]');c.setAttribute('aria-pressed',D);_.dataset.theme=D?'light':'dark'},h=(n,aE=0)=>+`${Math.round(`${n}e${aE}`)}e-${aE}`,m=(function(bA){let bB;function bC(e){bB=e.target;let bE=l(bB.value);!bE?document.querySelector('.input-wrapper').classList.add('user-invalid'):document.querySelector('.input-wrapper').classList.remove('user-invalid');bA.forEach.call(document.getElementsByClassName(bB.getAttribute('data-table')),function(bF){bA.forEach.call(bF.tBodies,function(bG){bA.forEach.call(bG.rows,bD)})})}function bD(bH){let bI=bH.textContent.toLowerCase();bH.style.display=bI.indexOf(bB.value.toLowerCase())===-1?'none':'table-row'}return{init:function(){bA.forEach.call(document.getElementsByClassName('light-table-filter'),function(bJ){bJ.oninput=bC})}}})(Array.prototype);window.addEventListener('offline',()=>A.classList.add('offline'));window.addEventListener('online',()=>A.classList.remove('offline'));var _=document.documentElement;(C=>{if(!window.matchMedia)return;var _b=window.matchMedia('(prefers-color-scheme: dark)');C(_b.matches)})(_a=>_a?_.setAttribute('data-theme','dark'):_.setAttribute('data-theme','light'));c.addEventListener('click',(()=>{!document.startViewTransition&&d();document.startViewTransition(d)}));window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',_A=>_.dataset.theme=_A.matches?'dark':'light');B().then(E=>i(E));async function B(){var aA=await fetch('https://recreatorus.github.io/countryinfo/data/countries.json',{priority:'high'});var _B=await aA.json();var _c=_B.map(({country:aB,pop2024:aC,area:_C,density:_d,gdp2024:_e,gdppc2024:F,gdpppppc2024:G,growthgdp2023:H})=>({country:aB,pop2024:aC,area:_C,density:_d,gdp2024:_e,gdppc2024:F,gdpppppc2024:G,growthgdp2023:H}));return _c}var f=document.querySelector('tbody');function g(aD){return new Intl.NumberFormat('ru-RU').format(aD)}function i(aF){for(const entry of aF){var aG=document.createElement('tr');aG.innerHTML=`
      <td>${entry.country}</td>
      <td>${g(entry.pop2024)}</td>
      <td>${g(entry.area)}</td>
      <td>${g(h(entry.density,1))}</td>
      <td>${g(h(entry.gdp2024,1))}</td>
      <td>${g(h(entry.gdppc2024,0))}</td>
      <td>${g(h(entry.gdpppppc2024,0))}</td>
    `;f.append(aG)}j()}function j(){const aH=document.getElementById('sortMe'),aI=aH.querySelectorAll('th'),aJ=aH.querySelector('tbody'),_D=aJ.querySelectorAll('tr');var _E=[...aI].map(header=>''),_f=function(aK,aL){const aM=aI[aK].getAttribute('data-type');switch(aM) {case 'number':return parseFloat(aL);case 'string':default:return aL}},_g=function(aN){const aO=_E[aN]||'asc',aP=aO==='asc'?1:-1,aQ=[..._D];aQ.sort((aR,aS)=>{const a=_f(aN,aR.querySelectorAll('td')[aN].innerHTML.replaceAll('\&nbsp;','')),b=_f(aN,aS.querySelectorAll('td')[aN].innerHTML.replaceAll('\&nbsp;',''));switch(!0) {case a>b:return 1*aP;case a<b:return -1*aP;case a===b:return 0}});[].forEach.call(_D,function(aT){aJ.removeChild(aT)});_E[aN]=aO==='asc'?'desc':'asc';for(const aU of aQ)aJ.appendChild(aU)};[].forEach.call(aI,function(aV,aW){aV.addEventListener('click',function(){_g(aW)})})}var k=document.querySelectorAll('#sortMe th');[].forEach.call(k,function(el){el.addEventListener('click',function(){[].forEach.call(k,function(aX){aX.classList.remove('active')});el.classList.add('active')})});function l(aY){for(const aZ of aY)if(!(aZ>='a'&&aZ<='z')&&!(aZ>='A'&&aZ<='Z'))return!1;return!0}document.addEventListener('readystatechange',function(){document.readyState==='complete'&&m.init()});document.getElementById('year').innerHTML=new Date().getFullYear();
